"""initial v1 schema

Revision ID: 217adf331603
Revises: 
Create Date: 2026-08-16 12:49:13.956972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '217adf331603'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_organization_name')
    )
    op.create_table('suppliers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_organization_id', 'suppliers', ['organization_id'], unique=False)
    op.create_index('uq_suppliers_organization_gstin', 'suppliers', ['organization_id', 'gstin'], unique=True, postgresql_where=sa.text('gstin IS NOT NULL'))
    op.create_table('account_transactions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (debit_amount = 0 AND credit_amount > 0)', name='ck_account_transactions_one_sided'),
    sa.CheckConstraint('credit_amount >= 0', name='ck_account_transactions_credit_non_negative'),
    sa.CheckConstraint('debit_amount >= 0', name='ck_account_transactions_debit_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_transactions_organization_id', 'account_transactions', ['organization_id'], unique=False)
    op.create_index('ix_account_transactions_supplier_id', 'account_transactions', ['supplier_id'], unique=False)
    op.create_index('ix_account_transactions_transaction_date', 'account_transactions', ['transaction_date'], unique=False)
    op.create_table('bills',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cgst_amount >= 0', name='ck_bills_cgst_non_negative'),
    sa.CheckConstraint('discount_amount <= subtotal', name='ck_bills_discount_not_greater_than_subtotal'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_bills_discount_non_negative'),
    sa.CheckConstraint('due_date IS NULL OR due_date >= bill_date', name='ck_bills_due_date_valid'),
    sa.CheckConstraint('igst_amount >= 0', name='ck_bills_igst_non_negative'),
    sa.CheckConstraint('sgst_amount >= 0', name='ck_bills_sgst_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_bills_subtotal_non_negative'),
    sa.CheckConstraint('taxable_amount >= 0', name='ck_bills_taxable_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_bills_total_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'supplier_id', 'bill_number', name='uq_bills_organization_supplier_number')
    )
    op.create_index('ix_bills_bill_date', 'bills', ['bill_date'], unique=False)
    op.create_index('ix_bills_due_date', 'bills', ['due_date'], unique=False)
    op.create_index('ix_bills_organization_id', 'bills', ['organization_id'], unique=False)
    op.create_index('ix_bills_status', 'bills', ['status'], unique=False)
    op.create_index('ix_bills_supplier_id', 'bills', ['supplier_id'], unique=False)
    op.create_table('payments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='recorded', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_organization_id', 'payments', ['organization_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('ix_payments_supplier_id', 'payments', ['supplier_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_adjustments',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_bill_adjustments_amount_positive'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bill_adjustments_bill_id', 'bill_adjustments', ['bill_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='PCS', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount <= quantity * unit_price', name='ck_bill_items_discount_not_greater_than_gross'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_bill_items_discount_non_negative'),
    sa.CheckConstraint('line_total >= 0', name='ck_bill_items_line_total_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_bill_items_quantity_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_bill_items_tax_non_negative'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='ck_bill_items_tax_rate_valid'),
    sa.CheckConstraint('unit_price >= 0', name='ck_bill_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bill_items_bill_id', 'bill_items', ['bill_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_allocations_bill_id', 'payment_allocations', ['bill_id'], unique=False)
    op.create_index('ix_payment_allocations_payment_id', 'payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_allocations_payment_id', table_name='payment_allocations')
    op.drop_index('ix_payment_allocations_bill_id', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('ix_bill_items_bill_id', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('ix_bill_adjustments_bill_id', table_name='bill_adjustments')
    op.drop_table('bill_adjustments')
    op.drop_table('audit_logs')
    op.drop_table('attachments')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('ix_payments_supplier_id', table_name='payments')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_organization_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_bills_supplier_id', table_name='bills')
    op.drop_index('ix_bills_status', table_name='bills')
    op.drop_index('ix_bills_organization_id', table_name='bills')
    op.drop_index('ix_bills_due_date', table_name='bills')
    op.drop_index('ix_bills_bill_date', table_name='bills')
    op.drop_table('bills')
    op.drop_index('ix_account_transactions_transaction_date', table_name='account_transactions')
    op.drop_index('ix_account_transactions_supplier_id', table_name='account_transactions')
    op.drop_index('ix_account_transactions_organization_id', table_name='account_transactions')
    op.drop_table('account_transactions')
    op.drop_index('uq_suppliers_organization_gstin', table_name='suppliers', postgresql_where=sa.text('gstin IS NOT NULL'))
    op.drop_index('ix_suppliers_organization_id', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
